### ISSUE TITLE
checkUnique returns 'Page not found' for available value

### ISSUE THREAD

**Issue by MHerszak** [feathersjs/feathers-authentication-management#14] opened 2017-02-09 17:52 UTC
Hi,

I am currently using this package and I am wondering if it was possible to handle errors ourselves? I am not obtaining a result on my end. Based on the source I am only getting an error when the value exists. Or I am getting a catch result with a general error. Would it be possible to obtain a result from the call? Here is my attempt.

```
export function checkUnique(data) {
  const obj = authData.checkUnique;
  const exportData = Object.assign({}, omit(obj, 'types'), data);
  return {
    types: obj.types,
    promise: () => authManagement.create(exportData)
      .then((result) => {
        console.log('checkUnique');
        return ({ data: result });
      })
      .catch(catchValidation)
  };
}
```
Thank you for this package!

**Comment by MHerszak** [comment] 2017-02-09 22:48
An "easy" fix would be to just add a callback to options. Just a thought.

**Comment by cpsubrian** [comment] 2017-04-18 04:50
To piggyback on this, the issue is that `checkUnique` has no result (`hook.result === undefined`) if it 'passes'. This causes the rest of the middleware chain to run and eventually results in a 404 (if your app bound a handler for that at the end).

My solution was to bind an after hook that simply provides a reasonable result like:

```js
// Initialize the authentication service.
app.configure(authenticationManagement(options))

// Add hooks.
app.service(options.path).hooks({
  before: {
    create: [
      hooks.iff(
        isAction('passwordChange', 'identityChange'),
        auth.verifyToken()
      ),
      hooks.iff(
        isAction('passwordChange', 'identityCange'),
        auth.populateUser()
      )
    ]
  },
  after: {
    create: [
      // @todo This is needed because of weird output of the service.
      function (hook) {
        switch (hook.data.action) {
          case 'checkUnique':
            hook.result = {status: 'OK'}
            break
        }
        return Promise.resolve(hook)
      }
    ]
  }
})
```

@daffl Is it intentional that this service **only** provides errors, and no result if the check passes?

**Comment by eddyystop** [comment] 2017-04-18 13:53
`checkUniqueness` is intended to be used for async frontend validation.
**It is not intended to be used as a service hook.**

One use case is a new user form with userName and email fields. You want to
make sure both are unique before submitting the form. So you do an async
call to `checkUniqueness`.

The call succeeds if both are unique. A superious `null` result is returned.

It throws an error if not. The `err` object contains { message: 'Values
already taken.', errors: { userName: 'Already taken.', email: 'Already
taken.'} }`

This is a standard async verification pattern, used by multiple form repos.
For example http://redux-form.com/6.6.3/examples/asyncValidation/

I'm not sure what other result could be returned on success.

**Comment by eddyystop** [comment] 2017-04-18 14:08
That being said, `feathers-authentication-management` is still a stand alone repo; its not integrated with `feathers-authentication`. That integration can't be donme until some authentication resources free up.

**Comment by cpsubrian** [comment] 2017-04-18 14:38
@eddyystop In my debugging the result was `undefined`, not `null`, and didn't return (with a `201`), it dropped through the rest of the express middleware. If I edit my example above and set `hook.result = null` instead of `{status: 'OK'}`, then feathers sends me a `204` with the null result instead of the `404`.

Note that https://github.com/feathersjs/feathers-authentication-management/blob/master/src/checkUniqueness.js#L29-L40 does not resolve with anything (`undefined`) if the check passes.

**Comment by cpsubrian** [comment] 2017-04-18 14:43
Made a PR in #24, if this is how we want to solve this.

**Comment by eddyystop** [comment] 2017-04-18 18:58
Merged https://github.com/feathersjs/feathers-authentication-management/pull/24

**Comment by eddyystop** [comment] 2017-04-18 19:02
Does this resolve this issue

@MHerszak Feathers tries to avoid callbacks. Promises and now await/async threaten the concept.

**Comment by MHerszak** [comment] 2017-04-20 02:22
@eddyystop I shall test. Thanks!

**Comment by eddyystop** [comment] 2017-04-20 12:54
Forget about:
- Perhaps we should expose a hook which wraps checkUnique?
- Any other pain points?

**Comment by cpsubrian** [comment] 2017-04-20 14:54
As for wrapping, what would that provide that the regular service hooks don't? They already wrap it with before and after. I was able to resolve my issue using an after hook, but I thought that the default being undefined didn't make sense hence the PR.

**Comment by MHerszak** [comment] 2017-05-08 18:34
@cpsubrian I am using it the same way now. Being able to add some clarifying errors or results has helped using hooks. Thanks! I guess we can close it now?

**Comment by cpsubrian** [comment] 2017-05-08 18:48
@MHerszak Definitely resolved for me now :smile:

**Comment by eddyystop** [comment] 2017-05-08 19:31
Thanks all!

**Closed by eddyystop** 2017-05-08 19:31 UTC
Labels: being discussed
